Bump scoverage version from 1.4.8 to 1.4.10 to fix Scala 2.12.15 compatibility
scoverage/gradle-scoverage pull request #175
Opened 2021-11-17 17:49 UTC by xkrogen

As described in #174, currently this plugin is broken when using Scala 2.12.15. This PR fixes it by bumping the scoverage version from 1.4.18 to 1.4.10.

2021-11-26 13:26 UTC, mwos-sl approved these changes

2021-12-01 16:44 UTC, xkrogen commented
@maiflai are you able to take a look at this?

2022-01-03 16:17 UTC, xkrogen commented
@maiflai or @eyalroth -- friendly ping on this

2022-01-11 21:32 UTC, gabrieljones requested changes

2022-01-11 21:32 UTC, gabrieljones commented on src/main/groovy/org/scoverage/ScoverageExtension.groovy
> +        scoverageVersion.set('1.4.10')
```suggestion
        scoverageVersion.set('1.4.11')
```
per https://github.com/scoverage/scalac-scoverage-plugin/releases/tag/v1.4.11

2022-08-21 21:32 UTC, merged